### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by Ein-Tim** [SKaplanOfficial/Raycast-PromptLab#11]
Hey, I just tried this extension and it is so good! Thank you very much! Is there any way that I can configure the AI (I'm using OpenAI API with my own key), to respond in German? Currently, even when I *feed* the AI with German content, it responds in English.

**Comment by SKaplanOfficial** [comment]
Adjusting the model schema seems to do the trick for me, just adding a request to translate all responses to German, i.e.:
```
{ "model": "gpt-3.5-turbo", "messages": [{"role": "user", "content": "{prompt}. Please translate your response to German, without repeating the prompt above."}], "stream": true }
```

<img width="1000" alt="promptlab-3" src="https://github.com/SKaplanOfficial/Raycast-PromptLab/assets/7865925/b3f91684-f5c2-49bf-b19a-4d58b77b21e9">

Alternatively, you can add the same instructions to the end of individual commands, which should work the same.

**Comment by SKaplanOfficial** [comment]
I've just added settings for Prompt Prefix and Prompt Suffix to easily apply context to all commands. It's essentially the same as what I did above, but works for people using Raycast AI as well.

**Comment by Ein-Tim** [comment]
That's great and works. Thank you!
