### ISSUE TITLE
Error: No executable JS file found

### ISSUE THREAD

**Issue by thuongtin** [SKaplanOfficial/Raycast-PromptLab#12]
Reason: No executable JS file found
Domain: commands
Time: 01:32:04.042
Recovery: Build the extension before usage
<img width="804" alt="image" src="https://github.com/SKaplanOfficial/Raycast-PromptLab/assets/3460591/daf03d90-b805-486b-a593-6712273e62f5">

**Comment by SKaplanOfficial** [comment]
What steps are you using to run it? Haven't seen this before and can't find much online about it.

**Comment by thuongtin** [comment]
- Clone the project
- Import extension
- npm install
- npm run dev

**Comment by thuongtin** [comment]
It's working properly now
