### ISSUE TITLE
Does It Support Chunking?

### ISSUE THREAD

**Issue by thuongtin** [SKaplanOfficial/Raycast-PromptLab#13]
This could improve performance and accuracy when dealing with large files or web pages.

**Comment by SKaplanOfficial** [comment]
Assuming you mean splitting files into smaller parts and sending them sequentially, then no, at least not yet. I might do something like that soon.  I'll likely have options for different strategies, e.g. chunking, removing least significant tokens, random token/line removal, etc.

**Comment by thuongtin** [comment]
Currently, I am using your extension to perform summaries and content analysis from websites, but the results are cut off and do not meet the requirements. I have also requested 100k tokens from Claude but I don't know if it will be approved.
It's not easy to be able to do a project like you. Keep developing.
