### ISSUE TITLE
Get no response with OpenAI

### ISSUE THREAD

**Issue by masx14** [SKaplanOfficial/Raycast-PromptLab#20]
I tried to run Commands with this extension

My configuration is as follows:

{ "model": "gpt-3.5-turbo", "messages": [{"role": "user", "content": "{prompt}"}]}

The problem is, that the request is sent, I am billed from OpenAI, but the extension says it got no responses.

**Comment by SKaplanOfficial** [comment]
Hey, try adding `"stream": true` at the end of the input schema, so it'd be `{ "model": "gpt-3.5-turbo", "messages": [{"role": "user", "content": "{prompt}"}], "stream": true }`. Sorry about that!
