### ISSUE TITLE
OpenAI endpoint issues with prompts

### ISSUE THREAD

**Issue by harnoor-saini** [SKaplanOfficial/Raycast-PromptLab#6]
Hello! I am using the OpenAI endpoint.
When I run `TechCrunch News` or `Summarize GitHub trending`, I get responses like 

> As an AI language model, I do not have the ability to analyze today’s trending GitHub repositories as they change frequently, but I can provide a summary of the current trending repositories based on the given link.

It seems the the content from the URL is not being parsed into the prompt.

**Comment by SKaplanOfficial** [comment]
This seems to be a slight change in how the OpenAI API responds -- if you copy the prompt sent to the model using `command+shift+P`, I believe you'll see that the URL content is being parsed, but the model just seems to ignore it.

If you don't see the URL content in the prompt, let me know. It might be a different issue altogether.

**Comment by SKaplanOfficial** [comment]
As for a fix, I'll see about adjusting the prompts. Likely just wants slightly different wording.

**Comment by harnoor-saini** [comment]
`cmd+shift+P` still gives the original url in curly braces. The `weather forecast` command is also interesting, `{{weather}}` is still present but `{{weekEvents}}` is expanded.

**Comment by SKaplanOfficial** [comment]
You're right, I accidentally broke URL placeholders earlier today. Should work correctly with the latest push. This also explains the odd behavior I was experiencing earlier. Let me know if you're still having problems after the update.
